"""1

Revision ID: d224c754afa1
Revises: 6ad96e00d085
Create Date: 2018-07-15 23:37:31.653066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd224c754afa1'
down_revision = '6ad96e00d085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=False))
    # ### end Alembic commands ###
