"""2

Revision ID: e43cad3b89b3
Revises: 06dc0028a035
Create Date: 2018-07-16 13:57:55.634684

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e43cad3b89b3'
down_revision = '06dc0028a035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_bin', length=128), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
